/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiEditor: typeof import('./../src/components/AiEditor.vue')['default']
    BubbleMenu: typeof import('../src/components/BubbleMenuItem.vue')['default']
    BubbleMenuItem: typeof import('./../src/components/BubbleMenuItem.vue')['default']
    ColorPicker: typeof import('./../src/components/ColorPicker.vue')['default']
    HelpCenter: typeof import('../src/components/More.vue')['default']
    InsertEmoji: typeof import('./../src/components/InsertEmoji.vue')['default']
    InsertHead: typeof import('./../src/components/InsertHead.vue')['default']
    InsertLink: typeof import('./../src/components/InsertLink.vue')['default']
    InsertTable: typeof import('./../src/components/InsertTable.vue')['default']
    InsetEmoji: typeof import('../src/components/InsertEmoji.vue')['default']
    Menu: typeof import('../src/components/BubbleMenuItem.vue')['default']
    More: typeof import('./../src/components/More.vue')['default']
    Popover: typeof import('./../src/components/Popover.vue')['default']
    Select: typeof import('./../src/components/Select.vue')['default']
    SetFont: typeof import('../src/components/SetTextSize.vue')['default']
    SetFontColor: typeof import('../src/components/SetTextSize.vue')['default']
    SetFontSize: typeof import('../src/components/SetTextSize.vue')['default']
    SetLineHeight: typeof import('../src/components/Select.vue')['default']
    SetNumber: typeof import('../src/components/Select.vue')['default']
    SetTextAlign: typeof import('./../src/components/SetTextAlign.vue')['default']
    SetTextSize: typeof import('./../src/components/SetTextSize.vue')['default']
    Table: typeof import('./../src/components/Table.vue')['default']
    Tabs: typeof import('./../src/components/Tabs.vue')['default']
    Toolbar: typeof import('./../src/components/Toolbar.vue')['default']
    Tooltip: typeof import('./../src/components/Tooltip.vue')['default']
    TreeSelect: typeof import('./../src/components/TreeSelect.vue')['default']
    Upload: typeof import('./../src/components/Upload.vue')['default']
  }
}
